//==================================================
//     Outputs that match the input variables
//==================================================
output "bucket_a_module" {
  description = "The value of the `bucket_a_module` input variable."
  value       = var.bucket_a_module
}
output "bucket_b_module" {
  description = "The value of the `bucket_b_module` input variable."
  value       = var.bucket_b_module
}
output "replicate_a_to_b" {
  description = "The value of the `replicate_a_to_b` input variable."
  value       = var.replicate_a_to_b
}
output "replicate_b_to_a" {
  description = "The value of the `replicate_b_to_a` input variable."
  value       = var.replicate_b_to_a
}
output "a_to_b_rules" {
  description = "The value of the `a_to_b_rules` input variable."
  value       = var.a_to_b_rules
}
output "b_to_a_rules" {
  description = "The value of the `b_to_a_rules` input variable."
  value       = var.b_to_a_rules
}


//==================================================
//       Outputs generated by this module
//==================================================
output "a_to_b_role" {
  description = "The `aws_iam_role` resource that was created for A-to-B replication, if A-to-B replication was enabled."
  value       = length(aws_iam_role.a_to_b) > 0 ? aws_iam_role.a_to_b[0] : null
}

output "b_to_a_role" {
  description = "The `aws_iam_role` resource that was created for B-to-A replication, if B-to-A replication was enabled."
  value       = length(aws_iam_role.b_to_a) > 0 ? aws_iam_role.b_to_a[0] : null
}

output "complete" {
  depends_on = [
    aws_s3_bucket_replication_configuration.a_to_b,
    aws_s3_bucket_replication_configuration.b_to_a,
  ]
  description = "Always `true`, but doesn't return until everything in this module has been applied."
  value       = true
}
